#!/usr/bin/env bash
set -euo pipefail

# Minerva Setup Script
# Generates a .env file by prompting for configuration values

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

echo "========================================"
echo "  Minerva - Setup"
echo "========================================"
echo ""

if [ -f "$ENV_FILE" ]; then
    read -p ".env already exists. Overwrite? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# Helper to prompt with a default value
prompt() {
    local var_name="$1"
    local prompt_text="$2"
    local default_value="${3:-}"
    local value

    if [ -n "$default_value" ]; then
        read -p "$prompt_text [$default_value]: " value
        value="${value:-$default_value}"
    else
        read -p "$prompt_text: " value
    fi
    eval "$var_name=\"$value\""
}

# Helper to prompt for a secret (no echo)
prompt_secret() {
    local var_name="$1"
    local prompt_text="$2"
    local value

    read -sp "$prompt_text: " value
    echo ""
    eval "$var_name=\"$value\""
}

echo "--- Required ---"
echo ""
prompt TELEGRAM_BOT_TOKEN "Telegram bot token (from @BotFather)"
prompt ADMIN_ID "Your Telegram user ID (from @userinfobot)"
echo ""

echo "--- Server ---"
echo ""
prompt BASE_URL "Public URL (e.g. https://minerva.example.com)" ""
prompt WEBHOOK_PORT "HTTP server port" "8080"
prompt DATABASE_PATH "SQLite database path" "./minerva.db"
echo ""

echo "--- Personalization ---"
echo ""
prompt OWNER_NAME "Your name (used in voice prompts)" ""
prompt DEFAULT_COUNTRY_CODE "Default country code" "+1"
echo ""

echo "--- Optional: Email (Resend) ---"
echo ""
read -p "Configure email? [y/N] " configure_email
RESEND_API_KEY=""
RESEND_WEBHOOK_SECRET=""
FROM_EMAIL=""
if [[ "$configure_email" =~ ^[Yy]$ ]]; then
    prompt_secret RESEND_API_KEY "Resend API key"
    prompt RESEND_WEBHOOK_SECRET "Resend webhook secret (optional)" ""
    prompt FROM_EMAIL "Sender address (e.g. Minerva <minerva@yourdomain.com>)" ""
fi
echo ""

echo "--- Optional: Voice Calls (Twilio) ---"
echo ""
read -p "Configure Twilio voice calls? [y/N] " configure_twilio
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_PHONE_NUMBER=""
if [[ "$configure_twilio" =~ ^[Yy]$ ]]; then
    prompt TWILIO_ACCOUNT_SID "Twilio Account SID"
    prompt_secret TWILIO_AUTH_TOKEN "Twilio Auth Token"
    prompt TWILIO_PHONE_NUMBER "Twilio phone number (e.g. +14155551234)"
fi
echo ""

echo "--- Optional: Voice AI (Gemini Live) ---"
echo ""
read -p "Configure Gemini Live voice AI? [y/N] " configure_gemini
GOOGLE_API_KEY=""
if [[ "$configure_gemini" =~ ^[Yy]$ ]]; then
    prompt_secret GOOGLE_API_KEY "Google AI API key"
fi
echo ""

echo "--- Optional: Remote Agents ---"
echo ""
read -p "Configure agent authentication? [y/N] " configure_agents
AGENT_PASSWORD=""
if [[ "$configure_agents" =~ ^[Yy]$ ]]; then
    prompt_secret AGENT_PASSWORD "Agent password"
fi
echo ""

echo "--- Optional: Encrypted Relay ---"
echo ""
read -p "Configure encrypted relay? [y/N] " configure_relay
RELAY_URL=""
RELAY_KEY=""
if [[ "$configure_relay" =~ ^[Yy]$ ]]; then
    prompt RELAY_URL "Relay WebSocket URL"
    prompt_secret RELAY_KEY "Relay authentication key"
fi
echo ""

# Write .env file
cat > "$ENV_FILE" << ENVEOF
# =============================================================================
# Minerva Configuration - Generated by setup.sh
# =============================================================================

# Required
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
ADMIN_ID=${ADMIN_ID}

# Server
BASE_URL=${BASE_URL}
WEBHOOK_PORT=${WEBHOOK_PORT}
DATABASE_PATH=${DATABASE_PATH}

# AI
MINERVA_WORKSPACE=./workspace

# Personalization
OWNER_NAME=${OWNER_NAME}
DEFAULT_COUNTRY_CODE=${DEFAULT_COUNTRY_CODE}

# Email (Resend)
RESEND_API_KEY=${RESEND_API_KEY}
RESEND_WEBHOOK_SECRET=${RESEND_WEBHOOK_SECRET}
FROM_EMAIL=${FROM_EMAIL}

# Voice Calls (Twilio)
TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}

# Voice AI (Gemini Live)
GOOGLE_API_KEY=${GOOGLE_API_KEY}

# Remote Agents
AGENT_PASSWORD=${AGENT_PASSWORD}

# Encrypted Relay
RELAY_URL=${RELAY_URL}
RELAY_KEY=${RELAY_KEY}

# Context
MAX_CONTEXT_MESSAGES=20
ENVEOF

chmod 600 "$ENV_FILE"

echo "========================================"
echo "  .env created at: $ENV_FILE"
echo "========================================"
echo ""
echo "Next steps:"
echo "  Docker:  docker compose up -d"
echo "  Binary:  go build -o minerva . && ./minerva"
echo ""
